{
 "PRed": [
  {
   "PR": {
    "__lazy_json__": "pr_json/265472086.json"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "0.6.1"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  }
 ],
 "archived": false,
 "bad": "make_graph: render error No module named 'toml'\nTraceback (most recent call last):\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/feedstock_parser.py\", line 241, in populate_feedstock_attributes\n    parse_meta_yaml(\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/utils.py\", line 167, in parse_meta_yaml\n    return _parse_meta_yaml_impl(\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/utils.py\", line 239, in _parse_meta_yaml_impl\n    m = MetaData(tmpdir, config=config, variant=var)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/conda_build/metadata.py\", line 932, in __init__\n    self.parse_again(permit_undefined_jinja=True, allow_no_other_outputs=True)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/conda_build/metadata.py\", line 1007, in parse_again\n    self.meta = parse(self._get_contents(permit_undefined_jinja,\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/conda_build/metadata.py\", line 1546, in _get_contents\n    from conda_build.jinja_context import context_processor, UndefinedNeverFail, FilteredLoader\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/conda_build/jinja_context.py\", line 13, in <module>\n    import toml\nModuleNotFoundError: No module named 'toml'\n",
 "branch": "main",
 "conda-forge.yml": {},
 "feedstock_name": "tornado-sqlalchemy",
 "hash_type": "sha256",
 "name": "tornado-sqlalchemy",
 "new_version": "0.7.0",
 "new_version_attempts": {
  "0.7.0": 2078
 },
 "new_version_errors": {
  "0.7.0": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '0.7.0' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tornado_sqlalchemy-{{ version }}.tar.gz'\n"
 },
 "outputs_names": {
  "__set__": true,
  "elements": [
   "tornado-sqlalchemy"
  ]
 },
 "pinning_version": "2019.03.17",
 "raw_meta_yaml": "{% set name = \"tornado-sqlalchemy\" %}\n{% set version = \"0.7.0\" %}\n\npackage:\n  name: \"{{ name|lower }}\"\n  version: \"{{ version }}\"\n\nsource:\n  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz\n  sha256: f37e59c376aa7661beb96992977c64e6b0baf5cbe74c41ccc0bf3b25dee0e637\n\nbuild:\n  noarch: python\n  number: 0\n  script: \"{{ PYTHON }} -m pip install . -vv\"\n\nrequirements:\n  host:\n    - pip\n    - poetry\n    - python >=3.5\n  run:\n    - python >=3.5\n    - sqlalchemy >=1.3\n    - tornado >=6.0\n\ntest:\n  imports:\n    - tornado_sqlalchemy\n\nabout:\n  home: https://github.com/siddhantgoel/tornado-sqlalchemy\n  license: MIT\n  license_family: MIT\n  license_file: LICENSE.txt\n  summary: SQLAlchemy helpers for working in Tornado\n  doc_url: https://tornado-sqlalchemy.readthedocs.io/\n  dev_url: https://github.com/siddhantgoel/tornado-sqlalchemy\n\nextra:\n  recipe-maintainers:\n    - lincrosenbach\n    - kfasolin\n    - nicoddemus\n",
 "smithy_version": "3.3.2",
 "strong_exports": false,
 "url": "https://pypi.io/packages/source/t/tornado-sqlalchemy/tornado-sqlalchemy-0.7.0.tar.gz",
 "version": "0.7.0"
}