{
  "done": [
    "shapely",
    "cartopy",
    "r-rgeos",
    "librttopo",
    "libspatialite",
    "gdal",
    "postgis",
    "basemap"
  ],
  "in-pr": [
    "pygeos",
    "qgis",
    "omniscidb"
  ],
  "awaiting-pr": [],
  "not-solvable": [
    "r-terra",
    "gmt"
  ],
  "awaiting-parents": [
    "r-exactextractr",
    "pyogrio"
  ],
  "bot-error": [],
  "_feedstock_status": {
    "basemap": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/basemap-feedstock/pull/86",
      "pr_status": "unstable"
    },
    "cartopy": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/cartopy-feedstock/pull/132",
      "pr_status": "unknown"
    },
    "gdal": {
      "num_descendants": 9,
      "immediate_children": [
        "gmt",
        "omniscidb",
        "postgis",
        "pyogrio",
        "qgis",
        "r-exactextractr",
        "r-terra",
        "rsgislib",
        "spdlib"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/gdal-feedstock/pull/577",
      "pr_status": "unknown"
    },
    "gmt": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/1499768977\">bot CI job</a>): master: ['linux_64_: Encountered problems while solving:\\n  - package gdal-3.3.3-py37h7b489ff_0 requires libgdal 3.3.3 h356f897_0, but none of the providers can be installed\\n', 'osx_64_: Encountered problems while solving:\\n  - package gdal-3.3.3-py37h005c65d_0 requires libgdal 3.3.3 h053b6da_0, but none of the providers can be installed\\n']"
    },
    "libspatialite": {
      "num_descendants": 11,
      "immediate_children": [
        "gdal",
        "libgdal",
        "qgis"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/libspatialite-feedstock/pull/80",
      "pr_status": "unknown"
    },
    "postgis": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/postgis-feedstock/pull/70",
      "pr_status": "unknown"
    },
    "qgis": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/qgis-feedstock/pull/216",
      "pr_status": "unstable"
    },
    "shapely": {
      "num_descendants": 1,
      "immediate_children": [
        "cartopy"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/shapely-feedstock/pull/93",
      "pr_status": "unknown"
    },
    "r-rgeos": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/r-rgeos-feedstock/pull/30",
      "pr_status": "unknown"
    },
    "pygeos": {
      "num_descendants": 1,
      "immediate_children": [
        "pyogrio"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/pygeos-feedstock/pull/48",
      "pr_status": "unstable"
    },
    "r-exactextractr": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": ""
    },
    "omniscidb": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/omniscidb-feedstock/pull/67",
      "pr_status": "clean"
    },
    "pyogrio": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": ""
    },
    "librttopo": {
      "num_descendants": 12,
      "immediate_children": [
        "libspatialite"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/librttopo-feedstock/pull/11",
      "pr_status": "unknown"
    },
    "r-terra": {
      "num_descendants": 1,
      "immediate_children": [
        "r-exactextractr"
      ],
      "pre_pr_migrator_status": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/1500315631\">bot CI job</a>): master: [\"LockError: \\nLOCKERROR: It looks like conda is already doing something.\\nThe lock ['/home/runner/conda_pkgs_dir/cache/b556ea5a.json.pid121124.conda_lock'] was found. Wait for it to finish before continuing.\\nIf you are sure that conda is not running, remove it and try again.\\nYou can also use: $ conda clean --lock\\n\"]"
    }
  }
}